"""call records

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uniqueid', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('linkedid', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('talk_seconds', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('disposition', sa.String(length=16), nullable=False),
    sa.Column('src_number', sa.String(length=64), nullable=False),
    sa.Column('src_name', sa.String(length=128), nullable=False),
    sa.Column('dst_number', sa.String(length=64), nullable=False),
    sa.Column('from_extension', sa.String(length=16), nullable=True),
    sa.Column('to_extension', sa.String(length=16), nullable=True),
    sa.Column('trunk', sa.String(length=64), nullable=True),
    sa.Column('route', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=128), nullable=False),
    sa.Column('dstchannel', sa.String(length=128), nullable=False),
    sa.Column('lastapp', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uniqueid', 'sequence')
    )
    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_records_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_dst_number'), ['dst_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_from_extension'), ['from_extension'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_linkedid'), ['linkedid'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_src_number'), ['src_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_to_extension'), ['to_extension'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_records_to_extension'))
        batch_op.drop_index(batch_op.f('ix_call_records_status'))
        batch_op.drop_index(batch_op.f('ix_call_records_started_at'))
        batch_op.drop_index(batch_op.f('ix_call_records_src_number'))
        batch_op.drop_index(batch_op.f('ix_call_records_linkedid'))
        batch_op.drop_index(batch_op.f('ix_call_records_from_extension'))
        batch_op.drop_index(batch_op.f('ix_call_records_dst_number'))
        batch_op.drop_index(batch_op.f('ix_call_records_direction'))

    op.drop_table('call_records')
    # ### end Alembic commands ###
